name: music_player
description: A music player app that plays audio from device storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.0
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
