name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [3.19.6]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Clean
        run: flutter clean

      - name: Flutter Analyze
        run: flutter analyze

      - name: Flutter Test
        run: flutter test

      - name: Build APK
        run: flutter build apk --release --no-shrink

      # Updated artifact upload step
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
